# -*- coding: utf-8 -*-
"""MyTikTok_CSV_Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CN4M8W5mC-nccXw6RztnKygtx-nw2Erg
"""

import sys
!{sys.executable} -m pip install pandas

print("pandas is installed.")

import pandas as pd
import re
from google.colab import files

# Global variable to store current DataFrame
current_df = None
current_filename = None

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def clear_screen():
    """Print newlines to simulate screen clear"""
    print("\n" * 2)

def display_main_menu():
    """Display the main menu options"""
    print("=" * 60)
    print("TikTok Affiliate CSV Manager")
    print("=" * 60)
    print("1. Create a new CSV file")
    print("2. Upload and edit an existing CSV file")
    print("3. Split a CSV file into smaller batch files")
    print("4. Extract TikTok usernames from pasted text")
    print("5. Exit")
    print("=" * 60)

def get_menu_choice(max_option):
    """Get valid menu choice from user"""
    while True:
        try:
            choice = input(f"Enter your choice (1-{max_option}): ").strip()
            choice_int = int(choice)
            if 1 <= choice_int <= max_option:
                return choice_int
            else:
                print(f"Please enter a number between 1 and {max_option}.")
        except ValueError:
            print("Invalid input. Please enter a number.")

def yes_no_prompt(prompt):
    """Get yes/no response from user"""
    while True:
        response = input(prompt + " (yes/no): ").strip().lower()
        if response in ['yes', 'y']:
            return True
        elif response in ['no', 'n']:
            return False
        else:
            print("Please enter 'yes' or 'no'.")

# ============================================================================
# FEATURE 1: CREATE NEW CSV FILE
# ============================================================================

def create_new_csv():
    """Create a new CSV file from scratch"""
    print("\n--- Create New CSV File ---")

    # Get number of columns
    while True:
        try:
            num_columns = int(input("How many columns do you want? ").strip())
            if num_columns > 0:
                break
            else:
                print("Please enter a positive number.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    # Get column names
    while True:
        column_input = input(f"Enter {num_columns} column names (comma-separated): ").strip()
        column_names = [col.strip() for col in column_input.split(',')]

        if len(column_names) == num_columns:
            break
        else:
            print(f"Error: You entered {len(column_names)} column names, but need {num_columns}.")

    # Create empty DataFrame
    df = pd.DataFrame(columns=column_names)
    print(f"\nCreated DataFrame with columns: {list(df.columns)}")

    # Add rows
    while True:
        print("\n--- Add Row ---")
        row_data = {}

        for col in column_names:
            value = input(f"Enter value for '{col}': ").strip()
            row_data[col] = value

        # Add row to DataFrame
        df = pd.concat([df, pd.DataFrame([row_data])], ignore_index=True)

        print("\nCurrent DataFrame:")
        print(df)

        if not yes_no_prompt("\nAdd another row?"):
            break

    # Editing options
    while True:
        print("\n--- Edit Options ---")
        print("1. Edit a row")
        print("2. Delete a row")
        print("3. View current table")
        print("4. Save and finish")

        edit_choice = get_menu_choice(4)

        if edit_choice == 1:
            # Edit row
            print(f"\nCurrent row indices: 0 to {len(df)-1}")
            try:
                row_index = int(input("Enter row index to edit: ").strip())
                if 0 <= row_index < len(df):
                    print(f"Current values: {df.iloc[row_index].to_dict()}")
                    for col in column_names:
                        new_value = input(f"Enter new value for '{col}' (press Enter to keep current): ").strip()
                        if new_value:
                            df.at[row_index, col] = new_value
                    print("\nUpdated DataFrame:")
                    print(df)
                else:
                    print("Invalid row index.")
            except ValueError:
                print("Invalid input.")

        elif edit_choice == 2:
            # Delete row
            print(f"\nCurrent row indices: 0 to {len(df)-1}")
            try:
                row_index = int(input("Enter row index to delete: ").strip())
                if 0 <= row_index < len(df):
                    if yes_no_prompt(f"Delete row {row_index}?"):
                        df = df.drop(row_index).reset_index(drop=True)
                        print("\nUpdated DataFrame:")
                        print(df)
                else:
                    print("Invalid row index.")
            except ValueError:
                print("Invalid input.")

        elif edit_choice == 3:
            # View table
            print("\nCurrent DataFrame:")
            print(df)

        elif edit_choice == 4:
            # Save and finish
            break

    # Save file
    filename = input("\nEnter filename (without .csv extension): ").strip()
    if not filename.endswith('.csv'):
        filename += '.csv'

    try:
        df.to_csv(filename, index=False, encoding='utf-8')
        print(f"\nFile saved as '{filename}'")
        files.download(filename)
        print("File downloaded successfully!")
    except Exception as e:
        print(f"Error saving file: {e}")

# ============================================================================
# FEATURE 2: UPLOAD AND EDIT EXISTING CSV
# ============================================================================

def upload_and_edit_csv():
    """Upload and edit an existing CSV file"""
    global current_df, current_filename

    print("\n--- Upload CSV File ---")

    try:
        # Upload file
        uploaded = files.upload()

        if not uploaded:
            print("No file uploaded.")
            return

        # Get filename
        current_filename = list(uploaded.keys())[0]

        # Load CSV
        current_df = pd.read_csv(current_filename)

        print(f"\nLoaded file: {current_filename}")
        print(f"Shape: {current_df.shape[0]} rows, {current_df.shape[1]} columns")
        print("\nFirst 10 rows:")
        print(current_df.head(10))
        print("\nColumns:", list(current_df.columns))

        # Editing menu
        edit_csv_menu()

    except Exception as e:
        print(f"Error loading file: {e}")
        current_df = None
        current_filename = None

def edit_csv_menu():
    """Display editing menu for uploaded CSV"""
    global current_df

    while True:
        print("\n--- Edit CSV Menu ---")
        print("1. Drop columns")
        print("2. Drop rows")
        print("3. Rename columns")
        print("4. Filter rows by column value")
        print("5. Show full DataFrame")
        print("6. Save and download edited file")
        print("7. Return to main menu")

        choice = get_menu_choice(7)

        if choice == 1:
            drop_columns()
        elif choice == 2:
            drop_rows()
        elif choice == 3:
            rename_columns()
        elif choice == 4:
            filter_rows()
        elif choice == 5:
            print("\nFull DataFrame:")
            print(current_df)
        elif choice == 6:
            save_edited_csv()
        elif choice == 7:
            break

def drop_columns():
    """Drop columns from DataFrame"""
    global current_df

    print("\nCurrent columns:", list(current_df.columns))
    columns_to_drop = input("Enter column names to drop (comma-separated): ").strip()

    if not columns_to_drop:
        print("No columns specified.")
        return

    column_list = [col.strip() for col in columns_to_drop.split(',')]

    # Validate columns exist
    invalid_cols = [col for col in column_list if col not in current_df.columns]

    if invalid_cols:
        print(f"Error: Columns not found: {invalid_cols}")
        return

    if yes_no_prompt(f"Drop columns {column_list}?"):
        try:
            current_df = current_df.drop(columns=column_list)
            print("Columns dropped successfully.")
            print("\nUpdated DataFrame:")
            print(current_df.head(10))
        except Exception as e:
            print(f"Error dropping columns: {e}")

def drop_rows():
    """Drop rows from DataFrame"""
    global current_df

    print(f"\nCurrent row indices: 0 to {len(current_df)-1}")
    rows_input = input("Enter row indices to drop (comma-separated): ").strip()

    if not rows_input:
        print("No rows specified.")
        return

    try:
        row_indices = [int(idx.strip()) for idx in rows_input.split(',')]

        # Validate indices
        invalid_indices = [idx for idx in row_indices if idx < 0 or idx >= len(current_df)]

        if invalid_indices:
            print(f"Error: Invalid row indices: {invalid_indices}")
            return

        if yes_no_prompt(f"Drop rows {row_indices}?"):
            current_df = current_df.drop(row_indices).reset_index(drop=True)
            print("Rows dropped successfully.")
            print("\nUpdated DataFrame:")
            print(current_df.head(10))

    except ValueError:
        print("Error: Invalid input. Please enter numbers separated by commas.")
    except Exception as e:
        print(f"Error dropping rows: {e}")

def rename_columns():
    """Rename columns in DataFrame"""
    global current_df

    print("\nCurrent columns:", list(current_df.columns))
    old_name = input("Enter current column name: ").strip()

    if old_name not in current_df.columns:
        print(f"Error: Column '{old_name}' not found.")
        return

    new_name = input("Enter new column name: ").strip()

    if not new_name:
        print("Error: New column name cannot be empty.")
        return

    try:
        current_df = current_df.rename(columns={old_name: new_name})
        print(f"Column '{old_name}' renamed to '{new_name}' successfully.")
        print("\nUpdated columns:", list(current_df.columns))
    except Exception as e:
        print(f"Error renaming column: {e}")

def filter_rows():
    """Filter rows by column value"""
    global current_df

    print("\nCurrent columns:", list(current_df.columns))
    column_name = input("Enter column name to filter by: ").strip()

    if column_name not in current_df.columns:
        print(f"Error: Column '{column_name}' not found.")
        return

    filter_value = input(f"Enter value to filter '{column_name}' by: ").strip()

    try:
        filtered_df = current_df[current_df[column_name].astype(str).str.contains(filter_value, case=False, na=False)]

        print(f"\nFiltered results ({len(filtered_df)} rows):")
        print(filtered_df.head(20))

        if len(filtered_df) > 0:
            if yes_no_prompt("Replace current DataFrame with filtered version?"):
                current_df = filtered_df.reset_index(drop=True)
                print("DataFrame updated with filtered results.")
        else:
            print("No matching rows found.")

    except Exception as e:
        print(f"Error filtering rows: {e}")

def save_edited_csv():
    """Save and download edited CSV"""
    global current_df

    filename = input("\nEnter filename for edited CSV (without .csv extension): ").strip()
    if not filename.endswith('.csv'):
        filename += '.csv'

    try:
        current_df.to_csv(filename, index=False, encoding='utf-8')
        print(f"\nFile saved as '{filename}'")
        files.download(filename)
        print("File downloaded successfully!")
    except Exception as e:
        print(f"Error saving file: {e}")

# ============================================================================
# FEATURE 3: SPLIT CSV INTO BATCH FILES
# ============================================================================

def split_csv_into_batches():
    """Split CSV file into smaller batch files"""
    global current_df

    print("\n--- Split CSV into Batches ---")

    # Check if DataFrame is loaded
    if current_df is None or current_df.empty:
        print("No CSV file currently loaded. Please upload a file.")
        try:
            uploaded = files.upload()
            if not uploaded:
                print("No file uploaded.")
                return

            filename = list(uploaded.keys())[0]
            current_df = pd.read_csv(filename)
            print(f"\nLoaded file: {filename}")
            print(f"Total rows: {len(current_df)}")

        except Exception as e:
            print(f"Error loading file: {e}")
            return

    # Get batch size
    batch_input = input("Enter number of rows per batch (default 100): ").strip()

    if not batch_input:
        batch_size = 100
    else:
        try:
            batch_size = int(batch_input)
            if batch_size <= 0:
                print("Error: Batch size must be positive.")
                return
        except ValueError:
            print("Error: Invalid number.")
            return

    # Calculate number of files
    total_rows = len(current_df)
    num_files = (total_rows + batch_size - 1) // batch_size

    print(f"\nTotal rows: {total_rows}")
    print(f"Batch size: {batch_size}")
    print(f"Number of files to create: {num_files}")

    if not yes_no_prompt("\nProceed with splitting?"):
        return

    # Split and save
    try:
        for i in range(0, total_rows, batch_size):
            batch_num = (i // batch_size) + 1
            batch_df = current_df.iloc[i:i+batch_size]

            filename = f"outreach_part_{batch_num}.csv"
            batch_df.to_csv(filename, index=False, encoding='utf-8')

            print(f"Created {filename} ({len(batch_df)} rows)")
            files.download(filename)

        print(f"\nSuccessfully created {num_files} batch files!")

    except Exception as e:
        print(f"Error splitting files: {e}")

# ============================================================================
# FEATURE 4: EXTRACT TIKTOK USERNAMES
# ============================================================================

def extract_tiktok_usernames():
    """Extract TikTok usernames from pasted text"""
    print("\n--- Extract TikTok Usernames ---")
    print("Paste your TikTok Shop creator text below.")
    print("When finished, type 'END' on a new line and press Enter.\n")

    lines = []
    while True:
        line = input()
        if line.strip().upper() == 'END':
            break
        lines.append(line)

    # Combine all text
    full_text = '\n'.join(lines)

    if not full_text.strip():
        print("No text provided.")
        return

    # Extract usernames using regex
    # Pattern: optional @, followed by letters, numbers, underscores, periods
    pattern = r'@?([a-zA-Z0-9_.]+)'
    matches = re.findall(pattern, full_text)

    # Clean up usernames
    usernames = []
    for match in matches:
        # Remove @ if present and strip whitespace
        username = match.strip()

        # Filter out very short matches (likely noise) and those without letters
        if len(username) >= 3 and any(c.isalpha() for c in username):
            usernames.append(username)

    # Remove duplicates and sort
    unique_usernames = sorted(list(set(usernames)))

    if not unique_usernames:
        print("No valid usernames found.")
        return

    print(f"\nTotal unique usernames found: {len(unique_usernames)}")
    print("\nFirst 20 usernames:")
    for i, username in enumerate(unique_usernames[:20], 1):
        print(f"{i}. {username}")

    if len(unique_usernames) > 20:
        print(f"... and {len(unique_usernames) - 20} more")

    # Create DataFrame
    df = pd.DataFrame({'username': unique_usernames})

    # Save file
    filename = input("\nEnter filename for username CSV (without .csv extension): ").strip()
    if not filename.endswith('.csv'):
        filename += '.csv'

    try:
        df.to_csv(filename, index=False, encoding='utf-8')
        print(f"\nFile saved as '{filename}'")
        files.download(filename)
        print("File downloaded successfully!")
    except Exception as e:
        print(f"Error saving file: {e}")

# ============================================================================
# MAIN FUNCTION
# ============================================================================

def main():
    """Main program loop"""
    print("Welcome to TikTok Affiliate CSV Manager!")
    print("This tool runs in Google Colab for easy CSV management.\n")

    while True:
        clear_screen()
        display_main_menu()

        choice = get_menu_choice(5)

        if choice == 1:
            create_new_csv()
        elif choice == 2:
            upload_and_edit_csv()
        elif choice == 3:
            split_csv_into_batches()
        elif choice == 4:
            extract_tiktok_usernames()
        elif choice == 5:
            print("\nThank you for using TikTok Affiliate CSV Manager!")
            print("Goodbye!")
            break

        if choice != 5:
            input("\nPress Enter to continue...")

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    main()